"""
Comprehensive Archetype Database, Card Pools, and Card Metadata Registry
for MTG Deckbuilder Generator and AI Optimizer.
Expanded with 25+ Commander Archetypes and 800+ metadata entries.
"""

from typing import Dict, List, Any, Optional, Tuple

# Card metadata registry: name -> (cmc, colors, type_line, estimated_usd)
CARD_METADATA_REGISTRY: Dict[str, Tuple[float, List[str], str, float]] = {
    # Commanders
    "Teysa Karlov": (4.0, ["W", "B"], "Legendary Creature — Human Advisor", 4.50),
    "Korvold, Fae-Cursed King": (5.0, ["B", "R", "G"], "Legendary Creature — Dragon Noble", 12.00),
    "Wilhelt, the Rotcleaver": (4.0, ["U", "B"], "Legendary Creature — Zombie Warrior", 7.50),
    "Judith, the Scourge Diva": (3.0, ["B", "R"], "Legendary Creature — Human Shaman", 0.75),
    "Elas il-Kor, Sadistic Pilgrim": (2.0, ["W", "B"], "Legendary Creature — Phyrexian Kor Cleric", 0.50),
    
    "Stella Lee, Wild Card": (3.0, ["U", "R"], "Legendary Creature — Human Rogue", 3.00),
    "Veyran, Voice of Duality": (3.0, ["U", "R"], "Legendary Creature — Efreet Wizard", 6.50),
    "Niv-Mizzet, Parun": (6.0, ["U", "R"], "Legendary Creature — Dragon Wizard", 2.00),
    "Birgi, God of Storytelling": (3.0, ["R"], "Legendary Creature — God", 12.00),
    "Birgi, God of Storytelling // Harnfel, Horn of Bounty": (3.0, ["R"], "Legendary Creature — God // Legendary Artifact", 12.00),
    "Kess, Dissident Mage": (4.0, ["U", "B", "R"], "Legendary Creature — Zombie Wizard", 1.50),
    "Norman Osborn // Green Goblin": (3.0, ["U", "B", "R"], "Legendary Creature — Human Scientist // Legendary Creature — Goblin Villain", 8.00),
    "Norman Osborn": (3.0, ["U", "B", "R"], "Legendary Creature — Human Scientist", 8.00),

    "Omnath, Locus of Creation": (4.0, ["W", "U", "R", "G"], "Legendary Creature — Elemental", 10.00),
    "Lord Windgrace": (5.0, ["B", "R", "G"], "Legendary Planeswalker — Windgrace", 8.00),
    "Aesi, Tyrant of Gyre Strait": (6.0, ["U", "G"], "Legendary Creature — Serpent Beast", 25.00),
    "The Gitrog Monster": (5.0, ["B", "G"], "Legendary Creature — Frog Horror", 6.00),
    "Titania, Protector of Argoth": (5.0, ["G"], "Legendary Creature — Elemental", 2.50),

    "The Ur-Dragon": (9.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Dragon Avatar", 28.00),
    "Miirym, Sentinel Wyrm": (6.0, ["U", "R", "G"], "Legendary Creature — Dragon", 5.00),
    "Lathliss, Dragon Queen": (6.0, ["R"], "Legendary Creature — Dragon", 2.50),
    "Scion of the Ur-Dragon": (5.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Dragon Avatar", 3.00),
    "Tiamat": (7.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Dragon God", 12.00),

    "Urza, Lord High Artificer": (4.0, ["U"], "Legendary Creature — Human Artificer", 12.00),
    "Breya, Etherium Shaper": (4.0, ["W", "U", "B", "R"], "Legendary Artifact Creature — Human", 8.00),
    "Jhoira, Weatherlight Captain": (4.0, ["U", "R"], "Legendary Creature — Human Artificer", 3.00),
    "Emry, Lurker of the Loch": (3.0, ["U"], "Legendary Creature — Merfolk Wizard", 2.50),
    "Sai, Master Thopterist": (3.0, ["U"], "Legendary Creature — Human Artificer", 1.25),

    "Kinnan, Bonder Prodigy": (2.0, ["U", "G"], "Legendary Creature — Human Druid", 15.00),
    "Najeela, the Blade-Blossom": (3.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Human Warrior", 11.00),
    "Rograkh, Son of Rohgahh": (0.0, ["R"], "Legendary Creature — Kobold Warrior", 2.50),
    "Silas Renn, Seeker Adept": (3.0, ["U", "B"], "Legendary Artifact Creature — Human", 4.00),
    "Thrasios, Triton Hero": (2.0, ["G", "U"], "Legendary Creature — Merfolk Wizard", 18.00),
    "Tymna the Weaver": (3.0, ["W", "B"], "Legendary Creature — Human Cleric", 35.00),
    "Kraum, Ludevic's Opus": (5.0, ["U", "R"], "Legendary Creature — Zombie Horror", 16.00),

    "Sram, Senior Edificer": (2.0, ["W"], "Legendary Creature — Dwarf Advisor", 1.00),
    "Galea, Kindler of Hope": (4.0, ["W", "U", "G"], "Legendary Creature — Elf Knight", 1.50),
    "Wyleth, Soul of Steel": (3.0, ["R", "W"], "Legendary Creature — Human Warrior", 2.50),
    "Light-Paws, Emperor's Voice": (2.0, ["W"], "Legendary Creature — Fox Advisor", 1.25),
    "Ardenn, Intrepid Archaeologist": (3.0, ["W"], "Legendary Creature — Kor Scout", 1.50),

    "Sythis, Harvest's Hand": (2.0, ["G", "W"], "Legendary Enchantment Creature — Nymph", 3.50),
    "Tuvasa the Sunlit": (3.0, ["W", "U", "G"], "Legendary Creature — Merfolk Shaman", 4.00),
    "Zur the Enchanter": (4.0, ["W", "U", "B"], "Legendary Creature — Human Wizard", 1.00),
    "Go-Shintai of Life's Origin": (4.0, ["W", "U", "B", "R", "G"], "Legendary Enchantment Creature — Shrine", 3.00),
    "Anikthea, Hand of Erebos": (5.0, ["W", "B", "G"], "Legendary Enchantment Creature — Demigod", 2.50),

    "Atraxa, Praetors' Voice": (4.0, ["W", "U", "B", "G"], "Legendary Creature — Phyrexian Angel", 18.00),
    "Vorinclex, Monstrous Raider": (6.0, ["G"], "Legendary Creature — Phyrexian Praetor", 38.00),
    "Marchesa, the Black Rose": (4.0, ["U", "B", "R"], "Legendary Creature — Human Noble", 1.50),
    "Shalai and Hallar": (4.0, ["R", "G", "W"], "Legendary Creature — Elf Angel", 2.50),
    "Ezuri, Claw of Progress": (4.0, ["U", "G"], "Legendary Creature — Elf Warrior", 2.00),

    "Rhys the Redeemed": (1.0, ["G", "W"], "Legendary Creature — Elf Warrior", 5.00),
    "Cadira, Caller of the Small": (3.0, ["G", "W"], "Legendary Creature — Orc Ranger", 0.50),
    "Jinnie Fay, Jetmir's Second": (3.0, ["R", "G", "W"], "Legendary Creature — Elf Druid", 1.50),
    "Krenko, Mob Boss": (4.0, ["R"], "Legendary Creature — Goblin Warrior", 7.00),
    "Marath, Will of the Wild": (3.0, ["R", "G", "W"], "Legendary Creature — Elemental Beast", 3.00),

    "Meren of Clan Nel Toth": (4.0, ["B", "G"], "Legendary Creature — Human Shaman", 4.00),
    "The Mimeoplasm": (5.0, ["U", "B", "G"], "Legendary Creature — Ooze", 2.00),
    "Chainer, Nightmare Adept": (4.0, ["B", "R"], "Legendary Creature — Human Minion", 0.75),
    "Sefris of the Hidden Ways": (3.0, ["W", "U", "B"], "Legendary Creature — Human Wizard", 1.50),

    "Brago, King Eternal": (4.0, ["W", "U"], "Legendary Creature — Spirit Soldier", 2.50),
    "Roon of the Hidden Realm": (5.0, ["W", "U", "G"], "Legendary Creature — Rhino Soldier", 0.75),
    "Yorion, Sky Nomad": (5.0, ["W", "U"], "Legendary Creature — Bird Serpent", 0.75),
    "Elesh Norn, Mother of Machines": (5.0, ["W"], "Legendary Creature — Phyrexian Praetor", 26.00),

    "Lathril, Blade of the Elves": (4.0, ["B", "G"], "Legendary Creature — Elf Noble", 4.00),
    "Marwyn, the Nurturer": (3.0, ["G"], "Legendary Creature — Elf Druid", 2.50),
    "Ezuri, Renegade Leader": (3.0, ["G"], "Legendary Creature — Elf Warrior", 6.00),
    "Selvala, Heart of the Wilds": (3.0, ["G"], "Legendary Creature — Elf Scout", 14.00),

    "Edgar Markov": (6.0, ["W", "B", "R"], "Legendary Creature — Vampire Noble", 95.00),
    "Vito, Thorn of the Dusk Rose": (3.0, ["B"], "Legendary Creature — Vampire Cleric", 6.00),
    "Strefan, Maurer Progenitor": (4.0, ["B", "R"], "Legendary Creature — Vampire Noble", 1.00),
    "Anowon, the Ruin Thief": (4.0, ["U", "B"], "Legendary Creature — Vampire Rogue", 1.00),

    "The Scarab God": (5.0, ["U", "B"], "Legendary Creature — God", 14.00),
    "Varina, Lich Queen": (4.0, ["W", "U", "B"], "Legendary Creature — Zombie Wizard", 3.00),
    "Gisa and Geralf": (4.0, ["U", "B"], "Legendary Creature — Human Wizard", 1.00),

    "Be'lakor, the Dark Master": (6.0, ["U", "B", "R"], "Legendary Creature — Demon Noble", 28.00),
    "Be'lakor": (6.0, ["U", "B", "R"], "Legendary Creature — Demon Noble", 28.00),
    "Belakor, the Dark Master": (6.0, ["U", "B", "R"], "Legendary Creature — Demon Noble", 28.00),
    "Belakor": (6.0, ["U", "B", "R"], "Legendary Creature — Demon Noble", 28.00),
    "Bela Kor": (6.0, ["U", "B", "R"], "Legendary Creature — Demon Noble", 28.00),
    "Giada, Font of Hope": (2.0, ["W"], "Legendary Creature — Angel", 4.00),
    "Pantlaza, Sun-Favored": (5.0, ["R", "G", "W"], "Legendary Creature — Dinosaur", 12.00),
    "Gishath, Sun's Avatar": (8.0, ["R", "G", "W"], "Legendary Creature — Dinosaur Avatar", 14.00),
    "The First Sliver": (5.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Sliver", 15.00),
    "Sliver Overlord": (5.0, ["W", "U", "B", "R", "G"], "Legendary Creature — Sliver Mutant", 40.00),
    "Inalla, Archmage Ritualist": (5.0, ["U", "B", "R"], "Legendary Creature — Human Wizard", 3.00),
    "Kaalia of the Vast": (4.0, ["W", "B", "R"], "Legendary Creature — Human Cleric", 15.00),
    "Yuriko, the Tiger's Shadow": (3.0, ["U", "B"], "Legendary Creature — Human Ninja", 2.50),

    # Demon Tribal Cards
    "Vilis, Broker of Blood": (8.0, ["B"], "Legendary Creature — Demon", 8.00),
    "Razaketh, the Foulblooded": (8.0, ["B"], "Legendary Creature — Demon", 14.00),
    "Archfiend of Despair": (8.0, ["B"], "Creature — Demon", 42.00),
    "Bloodthirster": (6.0, ["R"], "Creature — Demon", 18.00),
    "Bloodletter of Aclazotz": (4.0, ["B"], "Creature — Demon", 22.00),
    "Burning-Rune Demon": (6.0, ["B"], "Creature — Demon Berserker", 3.00),
    "Lord of the Void": (7.0, ["B"], "Creature — Demon", 16.00),
    "Herald of Torment": (3.0, ["B"], "Enchantment Creature — Demon", 0.50),
    "Rakdos, the Showstopper": (6.0, ["B", "R"], "Legendary Creature — Demon", 2.00),
    "Rune-Scarred Demon": (7.0, ["B"], "Creature — Demon", 4.00),
    "Kothophed, Soul Hoarder": (6.0, ["B"], "Legendary Creature — Demon", 0.50),
    "Demon of Dark Schemes": (6.0, ["B"], "Creature — Demon", 2.50),
    "Raphael, Fiendish Savior": (5.0, ["B", "R"], "Legendary Creature — Demon Tiefling", 1.50),
    "Doom Whisperer": (5.0, ["B"], "Creature — Demon Nightmare", 2.00),
    "Harvester of Souls": (6.0, ["B"], "Creature — Demon", 0.75),
    "Reaper from the Abyss": (6.0, ["B"], "Creature — Demon", 1.25),
    "Archfiend of Ifnir": (5.0, ["B"], "Creature — Demon", 4.00),
    "Taborax, Hope's Demise": (3.0, ["B"], "Legendary Creature — Demon Cleric", 0.50),
    "Liliana's Contract": (5.0, ["B"], "Enchantment", 1.50),
    "Warstorm Surge": (6.0, ["R"], "Enchantment", 0.75),
    "Reflections of Littjara": (5.0, ["U"], "Enchantment", 2.50),
    "Herald's Horn": (3.0, [], "Artifact", 6.00),
    "Urza's Incubator": (3.0, [], "Artifact", 28.00),
    "Vanquisher's Banner": (5.0, [], "Artifact", 5.00),
    "Kindred Discovery": (5.0, ["U"], "Enchantment", 9.00),
    "Patriarch's Bidding": (5.0, ["B"], "Sorcery", 3.50),
    "Haunting Voyage": (6.0, ["B"], "Sorcery", 4.00),
    "Roaming Throne": (4.0, [], "Artifact Creature — Golem", 28.00),
    "Metallic Mimic": (2.0, [], "Artifact Creature — Shapeshifter", 8.00),
    "Adaptive Automaton": (3.0, [], "Artifact Creature — Construct", 1.50),
    "Door of Destinies": (4.0, [], "Artifact", 12.00),
    "Cavern of Souls": (0.0, [], "Land", 38.00),
    "Unclaimed Territory": (0.0, [], "Land", 0.75),
    "Secluded Courtyard": (0.0, [], "Land", 1.00),
    "Mutavault": (0.0, [], "Land", 9.00),

    "Muxus, Goblin Grandee": (6.0, ["R"], "Legendary Creature — Goblin Noble", 9.00),
    "Zada, Hedron Grinder": (4.0, ["R"], "Legendary Creature — Goblin Ally", 0.35),

    "Grand Arbiter Augustin IV": (4.0, ["W", "U"], "Legendary Creature — Human Advisor", 4.00),
    "Winota, Joiner of Forces": (4.0, ["R", "W"], "Legendary Creature — Human Warrior", 5.00),
    "Lavinia, Azorius Renegade": (2.0, ["W", "U"], "Legendary Creature — Human Soldier", 0.50),
    "Derevi, Empyrial Tactician": (3.0, ["W", "U", "G"], "Legendary Creature — Bird Wizard", 4.00),

    "Nekusar, the Mindrazer": (5.0, ["U", "B", "R"], "Legendary Creature — Zombie Wizard", 8.00),
    "Xyris, the Writhing Storm": (5.0, ["U", "R", "G"], "Legendary Creature — Snake Leviathan", 2.50),
    "The Locust God": (6.0, ["U", "R"], "Legendary Creature — God", 2.00),
    "Sheoldred, the Apocalypse": (4.0, ["B"], "Legendary Creature — Phyrexian Praetor", 75.00),

    "Captain N'ghathrod": (5.0, ["U", "B"], "Legendary Creature — Horror Pirate", 18.00),
    "Phenax, God of Deception": (5.0, ["U", "B"], "Legendary Enchantment Creature — God", 12.00),
    "Bruvac the Grandiloquent": (3.0, ["U"], "Legendary Creature — Human Advisor", 22.00),

    "Yidris, Maelstrom Wielder": (4.0, ["U", "B", "R", "G"], "Legendary Creature — Ogre Wizard", 4.00),
    "Prosper, Tome-Bound": (4.0, ["B", "R"], "Legendary Creature — Tiefling Warlock", 9.00),
    "Maelstrom Wanderer": (8.0, ["U", "R", "G"], "Legendary Creature — Elemental", 2.50),

    "Kozilek, the Great Distortion": (10.0, [], "Legendary Creature — Eldrazi", 9.00),
    "Zhulodok, Void Gorger": (6.0, [], "Legendary Creature — Eldrazi", 14.00),
    "Ulamog, the Ceaseless Hunger": (10.0, [], "Legendary Creature — Eldrazi", 42.00),

    "K'rrik, Son of Yawgmoth": (7.0, ["B"], "Legendary Creature — Phyrexian Minion", 8.00),

    # Fast Mana & Rocks
    "Sol Ring": (1.0, [], "Artifact", 1.50),
    "Arcane Signet": (2.0, [], "Artifact", 0.75),
    "Fellwar Stone": (2.0, [], "Artifact", 1.00),
    "Thought Vessel": (2.0, [], "Artifact", 1.50),
    "Mind Stone": (2.0, [], "Artifact", 0.50),
    "Commander's Sphere": (3.0, [], "Artifact", 0.25),
    "Mana Crypt": (0.0, [], "Artifact", 180.00),
    "Mana Vault": (1.0, [], "Artifact", 45.00),
    "Chrome Mox": (0.0, [], "Artifact", 95.00),
    "Mox Diamond": (0.0, [], "Artifact", 600.00),
    "Mox Amber": (0.0, [], "Artifact", 45.00),
    "Mox Opal": (0.0, [], "Artifact", 90.00),
    "Lotus Petal": (0.0, [], "Artifact", 20.00),
    "Lion's Eye Diamond": (0.0, [], "Artifact", 450.00),
    "Basalt Monolith": (3.0, [], "Artifact", 3.00),
    "Grim Monolith": (2.0, [], "Artifact", 250.00),
    "Jeweled Lotus": (0.0, [], "Artifact", 75.00),
    "Smothering Tithe": (4.0, ["W"], "Enchantment", 22.00),
    "Jeska's Will": (3.0, ["R"], "Sorcery", 18.00),
    "Dockside Extortionist": (2.0, ["R"], "Creature — Goblin Pirate", 85.00),
    "Birds of Paradise": (1.0, ["G"], "Creature — Bird", 6.00),
    "Llanowar Elves": (1.0, ["G"], "Creature — Elf Druid", 0.35),
    "Elvish Mystic": (1.0, ["G"], "Creature — Elf Druid", 0.35),
    "Fyndhorn Elves": (1.0, ["G"], "Creature — Elf Druid", 0.50),
    "Nature's Lore": (2.0, ["G"], "Sorcery", 1.50),
    "Three Visits": (2.0, ["G"], "Sorcery", 4.00),
    "Farseek": (2.0, ["G"], "Sorcery", 1.25),
    "Cultivate": (3.0, ["G"], "Sorcery", 0.50),
    "Kodama's Reach": (3.0, ["G"], "Sorcery", 0.50),
    "Dark Ritual": (1.0, ["B"], "Instant", 1.00),
    "Cabal Ritual": (2.0, ["B"], "Instant", 8.00),
    "Culling the Weak": (1.0, ["B"], "Instant", 8.00),
    "Simian Spirit Guide": (3.0, ["R"], "Creature — Ape Spirit", 1.50),
    "Elvish Spirit Guide": (3.0, ["G"], "Creature — Elf Spirit", 1.50),
    "Manamorphose": (2.0, ["R", "G"], "Instant", 4.00),

    # Tutors
    "Demonic Tutor": (2.0, ["B"], "Sorcery", 35.00),
    "Vampiric Tutor": (1.0, ["B"], "Instant", 40.00),
    "Imperial Seal": (1.0, ["B"], "Sorcery", 80.00),
    "Grim Tutor": (3.0, ["B"], "Sorcery", 15.00),
    "Diabolic Intent": (2.0, ["B"], "Sorcery", 6.00),
    "Beseech the Mirror": (4.0, ["B"], "Sorcery", 25.00),
    "Mystical Tutor": (1.0, ["U"], "Instant", 9.00),
    "Personal Tutor": (1.0, ["U"], "Sorcery", 6.00),
    "Solve the Equation": (3.0, ["U"], "Sorcery", 2.00),
    "Merchant Scroll": (2.0, ["U"], "Sorcery", 4.00),
    "Enlightened Tutor": (1.0, ["W"], "Instant", 20.00),
    "Idyllic Tutor": (3.0, ["W"], "Sorcery", 4.50),
    "Open the Armory": (2.0, ["W"], "Sorcery", 1.50),
    "Worldly Tutor": (1.0, ["G"], "Instant", 12.00),
    "Green Sun's Zenith": (1.0, ["G"], "Sorcery", 11.00),
    "Finale of Devastation": (2.0, ["G"], "Sorcery", 28.00),
    "Chord of Calling": (3.0, ["G"], "Instant", 6.00),
    "Gamble": (1.0, ["R"], "Sorcery", 10.00),
    "Crop Rotation": (1.0, ["G"], "Instant", 2.50),

    # Draw & Engines
    "Rhystic Study": (3.0, ["U"], "Enchantment", 35.00),
    "Mystic Remora": (1.0, ["U"], "Enchantment", 7.00),
    "Esper Sentinel": (1.0, ["W"], "Creature — Human Soldier", 25.00),
    "The One Ring": (4.0, [], "Legendary Artifact", 90.00),
    "Skullclamp": (1.0, [], "Artifact — Equipment", 6.00),
    "Sylvan Library": (2.0, ["G"], "Enchantment", 24.00),
    "Necropotence": (3.0, ["B"], "Enchantment", 30.00),
    "Phyrexian Arena": (3.0, ["B"], "Enchantment", 2.50),
    "Black Market Connections": (3.0, ["B"], "Enchantment", 22.00),
    "Night's Whisper": (2.0, ["B"], "Sorcery", 1.50),
    "Sign in Blood": (2.0, ["B"], "Sorcery", 0.50),
    "Read the Bones": (3.0, ["B"], "Sorcery", 0.35),
    "Trouble in Pairs": (4.0, ["W"], "Enchantment", 20.00),
    "Archivist of Oghma": (2.0, ["W"], "Creature — Halfling Cleric", 7.00),
    "Beast Whisperer": (4.0, ["G"], "Creature — Elf Druid", 2.50),
    "Guardian Project": (4.0, ["G"], "Enchantment", 8.00),
    "Toski, Bearer of Secrets": (4.0, ["G"], "Legendary Creature — Squirrel", 6.00),
    "Wheel of Fortune": (3.0, ["R"], "Sorcery", 250.00),
    "Windfall": (3.0, ["U"], "Sorcery", 2.00),
    "Brainstorm": (1.0, ["U"], "Instant", 1.00),
    "Ponder": (1.0, ["U"], "Sorcery", 2.00),
    "Preordain": (1.0, ["U"], "Sorcery", 1.00),
    "Gitaxian Probe": (1.0, ["U"], "Sorcery", 3.00),
    "Frantic Search": (3.0, ["U"], "Instant", 0.75),
    "Expressive Iteration": (2.0, ["U", "R"], "Sorcery", 1.50),
    "Faithless Looting": (1.0, ["R"], "Sorcery", 0.50),
    "Thrill of Possibility": (2.0, ["R"], "Instant", 0.25),
    "Aetherflux Reservoir": (4.0, [], "Artifact", 14.00),
    "Underworld Breach": (2.0, ["R"], "Enchantment", 12.00),
    "Twisted Fealty": (3.0, ["R"], "Sorcery", 0.25),
    "Twinflame": (2.0, ["R"], "Sorcery", 4.00),
    "Dualcaster Mage": (3.0, ["R"], "Creature — Human Wizard", 0.75),
    "Guttersnipe": (3.0, ["R"], "Creature — Goblin Shaman", 0.35),
    "Archmage Emeritus": (4.0, ["U"], "Creature — Human Wizard", 4.00),
    "Storm-Kiln Artist": (4.0, ["R"], "Creature — Dwarf Shaman", 1.50),

    # Interaction & Removal
    "Swords to Plowshares": (1.0, ["W"], "Instant", 1.50),
    "Path to Exile": (1.0, ["W"], "Instant", 1.25),
    "Generous Gift": (3.0, ["W"], "Instant", 0.75),
    "Farewell": (6.0, ["W"], "Sorcery", 8.00),
    "Wrath of God": (4.0, ["W"], "Sorcery", 3.00),
    "Teferi's Protection": (3.0, ["W"], "Instant", 35.00),
    "Grand Abolisher": (2.0, ["W"], "Creature — Human Cleric", 12.00),
    "Silence": (1.0, ["W"], "Instant", 7.00),
    "Flawless Maneuver": (3.0, ["W"], "Instant", 10.00),
    "Cyclonic Rift": (2.0, ["U"], "Instant", 32.00),
    "Pongify": (1.0, ["U"], "Instant", 3.50),
    "Rapid Hybridization": (1.0, ["U"], "Instant", 1.50),
    "Resculpt": (2.0, ["U"], "Instant", 0.50),
    "Counterspell": (2.0, ["U"], "Instant", 1.00),
    "Swan Song": (1.0, ["U"], "Instant", 9.00),
    "Fierce Guardianship": (3.0, ["U"], "Instant", 40.00),
    "Mana Drain": (2.0, ["U"], "Instant", 38.00),
    "Force of Will": (5.0, ["U"], "Instant", 65.00),
    "Force of Negation": (3.0, ["U"], "Instant", 35.00),
    "Mindbreak Trap": (4.0, ["U"], "Instant", 45.00),
    "Pact of Negation": (0.0, ["U"], "Instant", 14.00),
    "Flusterstorm": (1.0, ["U"], "Instant", 18.00),
    "Mental Misstep": (1.0, ["U"], "Instant", 8.00),
    "An Offer You Can't Refuse": (1.0, ["U"], "Instant", 1.50),
    "Beast Within": (3.0, ["G"], "Instant", 1.25),
    "Nature's Claim": (1.0, ["G"], "Instant", 1.00),
    "Heroic Intervention": (2.0, ["G"], "Instant", 8.50),
    "Toxic Deluge": (3.0, ["B"], "Sorcery", 12.00),
    "Deadly Rollick": (4.0, ["B"], "Instant", 24.00),
    "Feed the Swarm": (2.0, ["B"], "Sorcery", 0.35),
    "Snuff Out": (4.0, ["B"], "Instant", 8.00),
    "Chaos Warp": (3.0, ["R"], "Instant", 1.00),
    "Deflecting Swat": (3.0, ["R"], "Instant", 45.00),
    "Lightning Bolt": (1.0, ["R"], "Instant", 0.50),
    "Blasphemous Act": (9.0, ["R"], "Sorcery", 2.50),
    "Abrade": (2.0, ["R"], "Instant", 0.25),

    # Lands
    "Command Tower": (0.0, [], "Land", 0.35),
    "Exotic Orchard": (0.0, [], "Land", 0.35),
    "City of Brass": (0.0, [], "Land", 18.00),
    "Mana Confluence": (0.0, [], "Land", 35.00),
    "Reflecting Pool": (0.0, [], "Land", 8.00),
    "Forbidden Orchard": (0.0, [], "Land", 6.00),
    "Path of Ancestry": (0.0, [], "Land", 0.25),
    "Ancient Tomb": (0.0, [], "Land", 85.00),
    "Urza's Saga": (0.0, [], "Enchantment Land — Urza's", 45.00),
    "War Room": (0.0, [], "Land", 3.00),
    "Reliquary Tower": (0.0, [], "Land", 1.50),
    "Strip Mine": (0.0, [], "Land", 18.00),
    "Scavenger Grounds": (0.0, [], "Land", 0.50),
    "Command Beacon": (0.0, [], "Land", 8.00),
    "Boseiju, Who Endures": (0.0, ["G"], "Legendary Land", 38.00),
    "Otawara, Soaring City": (0.0, ["U"], "Legendary Land", 18.00),
    "Takenuma, Abandoned Mire": (0.0, ["B"], "Legendary Land", 8.00),
    "Eiganjo, Seat of the Empire": (0.0, ["W"], "Legendary Land", 9.00),
    "Sokenzan, Crucible of Defiance": (0.0, ["R"], "Legendary Land", 4.00),
    "Cabal Coffers": (0.0, [], "Land", 20.00),
    "Urborg, Tomb of Yawgmoth": (0.0, [], "Legendary Land", 38.00),
    "Yavimaya, Cradle of Growth": (0.0, [], "Legendary Land", 8.00),

    # Shocklands
    "Hallowed Fountain": (0.0, ["W", "U"], "Land — Plains Island", 12.00),
    "Godless Shrine": (0.0, ["W", "B"], "Land — Plains Swamp", 11.00),
    "Sacred Foundry": (0.0, ["W", "R"], "Land — Plains Mountain", 14.00),
    "Temple Garden": (0.0, ["W", "G"], "Land — Forest Plains", 12.00),
    "Watery Grave": (0.0, ["U", "B"], "Land — Island Swamp", 13.00),
    "Steam Vents": (0.0, ["U", "R"], "Land — Island Mountain", 15.00),
    "Breeding Pool": (0.0, ["U", "G"], "Land — Forest Island", 16.00),
    "Blood Crypt": (0.0, ["B", "R"], "Land — Swamp Mountain", 14.00),
    "Overgrown Tomb": (0.0, ["B", "G"], "Land — Swamp Forest", 11.00),
    "Stomping Ground": (0.0, ["R", "G"], "Land — Mountain Forest", 12.00),

    # Fetchlands
    "Flooded Strand": (0.0, [], "Land", 16.00),
    "Polluted Delta": (0.0, [], "Land", 16.00),
    "Bloodstained Mire": (0.0, [], "Land", 16.00),
    "Wooded Foothills": (0.0, [], "Land", 16.00),
    "Windswept Heath": (0.0, [], "Land", 16.00),
    "Marsh Flats": (0.0, [], "Land", 14.00),
    "Scalding Tarn": (0.0, [], "Land", 18.00),
    "Verdant Catacombs": (0.0, [], "Land", 18.00),
    "Arid Mesa": (0.0, [], "Land", 14.00),
    "Misty Rainforest": (0.0, [], "Land", 20.00),

    # Basics
    "Plains": (0.0, ["W"], "Basic Land — Plains", 0.10),
    "Island": (0.0, ["U"], "Basic Land — Island", 0.10),
    "Swamp": (0.0, ["B"], "Basic Land — Swamp", 0.10),
    "Mountain": (0.0, ["R"], "Basic Land — Mountain", 0.10),
    "Forest": (0.0, ["G"], "Basic Land — Forest", 0.10),
    "Wastes": (0.0, [], "Basic Land", 0.50),

    # Additional Popular Staples & Commanders
    "Samut, Tyrant of Naktamun": (3.0, ["R", "G", "W"], "Legendary Creature — Human Warrior", 2.00),
    "Geist of Saint Traft": (3.0, ["W", "U"], "Legendary Creature — Spirit Cleric", 1.50),
    "Stella Lee, Wild Card": (3.0, ["U", "R"], "Legendary Creature — Human Rogue", 2.50),
    "Norman Osborn // Green Goblin": (2.0, ["U", "B", "R"], "Legendary Creature — Human Scientist", 1.00),
    "Norman Osborn": (2.0, ["U", "B", "R"], "Legendary Creature — Human Scientist", 1.00),
    "Big Score": (4.0, ["R"], "Instant", 0.50),
    "Unexpected Windfall": (4.0, ["R"], "Instant", 0.50),
    "Thassa's Oracle": (2.0, ["U"], "Creature — Merfolk Wizard", 20.00),
    "Tainted Pact": (2.0, ["B"], "Instant", 16.00),
    "Gifts Ungiven": (4.0, ["U"], "Instant", 2.00),
    "Inti, Seneschal of the Sun": (2.0, ["R"], "Legendary Creature — Human Knight", 4.00),
    "Artist's Talent": (2.0, ["R"], "Class Enchantment", 5.00),
    "Ledger Shredder": (2.0, ["U"], "Creature — Bird Advisor", 10.00),
    "Birgi, God of Storytelling // Harnfel, Horn of Bounty": (3.0, ["R"], "Legendary Creature — God", 8.00),
    "Birgi, God of Storytelling": (3.0, ["R"], "Legendary Creature — God", 8.00),
    "Blood for the Blood God!": (11.0, ["B", "R"], "Instant", 8.00),
    "Borne Upon a Wind": (2.0, ["U"], "Instant", 3.00),
    "Brain Freeze": (2.0, ["U"], "Instant", 4.00),
    "Chain of Vapor": (1.0, ["U"], "Instant", 6.00),
    "Chromatic Lantern": (3.0, [], "Artifact", 3.00),
    "Deadpool, Trading Card": (3.0, ["B", "R"], "Legendary Creature", 2.00),
    "Demonic Consultation": (1.0, ["B"], "Instant", 14.00),
    "Diabolic Tutor": (4.0, ["B"], "Sorcery", 0.50),
    "Emet-Selch of the Third Seat": (4.0, ["U", "B", "R"], "Legendary Creature", 2.00),
    "Luxury Suite": (0.0, ["B", "R"], "Land", 12.00),
    "Morphic Pool": (0.0, ["U", "B"], "Land", 14.00),
    "Sea of Clouds": (0.0, ["W", "U"], "Land", 10.00),
    "Spectator Seating": (0.0, ["W", "R"], "Land", 11.00),
    "Training Center": (0.0, ["U", "R"], "Land", 12.00),
    "Undergrowth Stadium": (0.0, ["B", "G"], "Land", 11.00),
    "Vault of Champions": (0.0, ["W", "B"], "Land", 12.00),
    "Spire Garden": (0.0, ["R", "G"], "Land", 10.00),
    "Bountiful Promenade": (0.0, ["W", "G"], "Land", 10.00),
    "Rejuvenating Springs": (0.0, ["U", "G"], "Land", 10.00),
}

# Color staples grouped by color & function
COLOR_STAPLES = {
    "W": {
        "ramp": [("Smothering Tithe", 4.0), ("Knight of the White Orchid", 2.0), ("Archaeomancer's Map", 3.0)],
        "draw": [("Esper Sentinel", 1.0), ("Trouble in Pairs", 4.0), ("Archivist of Oghma", 2.0)],
        "removal": [("Swords to Plowshares", 1.0), ("Path to Exile", 1.0), ("Generous Gift", 3.0), ("Farewell", 6.0), ("Wrath of God", 4.0)],
        "protection_combos": [("Teferi's Protection", 3.0), ("Grand Abolisher", 2.0), ("Silence", 1.0), ("Flawless Maneuver", 3.0)],
        "tutors": [("Enlightened Tutor", 1.0), ("Idyllic Tutor", 3.0), ("Open the Armory", 2.0)],
    },
    "U": {
        "ramp": [("High Tide", 1.0)],
        "draw": [("Rhystic Study", 3.0), ("Mystic Remora", 1.0), ("Windfall", 3.0), ("Brainstorm", 1.0), ("Ponder", 1.0), ("Preordain", 1.0), ("Gitaxian Probe", 1.0), ("Frantic Search", 3.0)],
        "removal": [("Cyclonic Rift", 2.0), ("Pongify", 1.0), ("Rapid Hybridization", 1.0), ("Resculpt", 2.0)],
        "counters": [("Counterspell", 2.0), ("Swan Song", 1.0), ("Fierce Guardianship", 3.0), ("Mana Drain", 2.0), ("Force of Will", 5.0), ("Force of Negation", 3.0), ("Pact of Negation", 0.0), ("Flusterstorm", 1.0), ("An Offer You Can't Refuse", 1.0)],
        "tutors": [("Mystical Tutor", 1.0), ("Personal Tutor", 1.0), ("Solve the Equation", 3.0), ("Merchant Scroll", 2.0)],
    },
    "B": {
        "ramp": [("Dark Ritual", 1.0), ("Cabal Ritual", 2.0), ("Culling the Weak", 1.0), ("Black Market Connections", 3.0)],
        "draw": [("Necropotence", 3.0), ("Phyrexian Arena", 3.0), ("Night's Whisper", 2.0), ("Sign in Blood", 2.0), ("Read the Bones", 3.0)],
        "removal": [("Toxic Deluge", 3.0), ("Deadly Rollick", 4.0), ("Feed the Swarm", 2.0), ("Snuff Out", 4.0)],
        "tutors": [("Demonic Tutor", 2.0), ("Vampiric Tutor", 1.0), ("Imperial Seal", 1.0), ("Grim Tutor", 3.0), ("Diabolic Intent", 2.0), ("Beseech the Mirror", 4.0)],
    },
    "R": {
        "ramp": [("Jeska's Will", 3.0), ("Dockside Extortionist", 2.0), ("Simian Spirit Guide", 3.0)],
        "draw": [("Wheel of Fortune", 3.0), ("Faithless Looting", 1.0), ("Thrill of Possibility", 2.0)],
        "removal": [("Chaos Warp", 3.0), ("Lightning Bolt", 1.0), ("Blasphemous Act", 9.0), ("Abrade", 2.0)],
        "protection_combos": [("Deflecting Swat", 3.0), ("Red Elemental Blast", 1.0), ("Pyroblast", 1.0)],
        "tutors": [("Gamble", 1.0)],
    },
    "G": {
        "ramp": [("Birds of Paradise", 1.0), ("Llanowar Elves", 1.0), ("Elvish Mystic", 1.0), ("Fyndhorn Elves", 1.0), ("Nature's Lore", 2.0), ("Three Visits", 2.0), ("Farseek", 2.0), ("Cultivate", 3.0), ("Kodama's Reach", 3.0), ("Elvish Spirit Guide", 3.0)],
        "draw": [("Sylvan Library", 2.0), ("Beast Whisperer", 4.0), ("Guardian Project", 4.0), ("Toski, Bearer of Secrets", 4.0)],
        "removal": [("Beast Within", 3.0), ("Nature's Claim", 1.0)],
        "protection_combos": [("Heroic Intervention", 2.0), ("Veil of Summer", 1.0)],
        "tutors": [("Worldly Tutor", 1.0), ("Green Sun's Zenith", 1.0), ("Finale of Devastation", 2.0), ("Chord of Calling", 3.0), ("Crop Rotation", 1.0)],
    },
    "Colorless": {
        "utility": [("The One Ring", 4.0), ("Skullclamp", 1.0), ("Aetherflux Reservoir", 4.0)],
    },
}

# 25+ Comprehensive Commander Archetypes
ARCHETYPE_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "Aristocrats / Sacrifice": {
        "theme": "Sacrificio de criaturas, drenaje masivo de vidas y recursión desde el cementerio",
        "commanders": [
            {"name": "Teysa Karlov", "color_identity": ["W", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Human Advisor", "reason": "Duplica todos los triggers de muerte (Deathharmonicon) y otorga vigilancia/vínculo vital."},
            {"name": "Korvold, Fae-Cursed King", "color_identity": ["B", "R", "G"], "cmc": 5.0, "type_line": "Legendary Creature — Dragon Noble", "reason": "Motor masivo de robo y crecimiento cada vez que sacrificas un permanente."},
            {"name": "Wilhelt, the Rotcleaver", "color_identity": ["U", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Zombie Warrior", "reason": "Genera tokens de zombis decrépitos y roba cartas al final del turno."},
            {"name": "Elas il-Kor, Sadistic Pilgrim", "color_identity": ["W", "B"], "cmc": 2.0, "type_line": "Legendary Creature — Phyrexian Kor Cleric", "reason": "Drenaje de 1 vida por cada criatura que entra o muere por solo 2 manás."},
        ],
        "synergy_cards": [
            ("Blood Artist", "Creature — Vampire", 2.0, ["B"], "Drain"),
            ("Zulaport Cutthroat", "Creature — Human Rogue", 2.0, ["B"], "Drain"),
            ("Cruel Celebrant", "Creature — Vampire", 2.0, ["W", "B"], "Drain"),
            ("Mayhem Devil", "Creature — Devil", 3.0, ["B", "R"], "Removal/Drain"),
            ("Viscera Seer", "Creature — Vampire Wizard", 1.0, ["B"], "Sac Outlet"),
            ("Carrion Feeder", "Creature — Zombie", 1.0, ["B"], "Sac Outlet"),
            ("Ashnod's Altar", "Artifact", 3.0, [], "Sac Outlet/Mana"),
            ("Phyrexian Altar", "Artifact", 3.0, [], "Sac Outlet/Mana"),
            ("Pitiless Plunderer", "Creature — Human Pirate", 4.0, ["B"], "Treasure Ramp"),
            ("Reassembling Skeleton", "Creature — Skeleton Warrior", 2.0, ["B"], "Fodder"),
            ("Bloodghast", "Creature — Vampire Spirit", 2.0, ["B"], "Fodder"),
            ("Dictate of Erebos", "Enchantment", 5.0, ["B"], "Removal Engine"),
            ("Grave Pact", "Enchantment", 4.0, ["B"], "Removal Engine"),
            ("Living Death", "Sorcery", 5.0, ["B"], "Mass Reanimation"),
            ("Lethal Scheme", "Instant", 4.0, ["B"], "Removal/Loot"),
        ],
        "combos": ["Gravecrawler + Phyrexian Altar + Blood Artist (Infinite Drain)", "Pitiless Plunderer + Reassembling Skeleton + Ashnod's Altar (Infinite Colorless/Treasures)"],
    },

    "Spellslinger / Storm": {
        "theme": "Lanzamiento encadenado de instantáneos/conjuros, copiado de hechizos y tormenta",
        "commanders": [
            {"name": "Stella Lee, Wild Card", "color_identity": ["U", "R"], "cmc": 3.0, "type_line": "Legendary Creature — Human Rogue", "reason": "Copia instantáneos/conjuros y genera victoria instantánea con Twisted Fealty."},
            {"name": "Veyran, Voice of Duality", "color_identity": ["U", "R"], "cmc": 3.0, "type_line": "Legendary Creature — Efreet Wizard", "reason": "Duplica todos los disparos de Magecraft y lanzamientos de instantáneos."},
            {"name": "Niv-Mizzet, Parun", "color_identity": ["U", "R"], "cmc": 6.0, "type_line": "Legendary Creature — Dragon Wizard", "reason": "Incounterable, roba al lanzar hechizos y genera daño infinito con Curiosity."},
            {"name": "Birgi, God of Storytelling", "color_identity": ["R"], "cmc": 3.0, "type_line": "Legendary Creature — God", "reason": "Añade {R} por cada hechizo lanzado, alimentando tormentas infinitas."},
        ],
        "synergy_cards": [
            ("Archmage Emeritus", "Creature — Human Wizard", 4.0, ["U"], "Card Draw"),
            ("Storm-Kiln Artist", "Creature — Dwarf Shaman", 4.0, ["R"], "Treasure Ramp"),
            ("Guttersnipe", "Creature — Goblin Shaman", 3.0, ["R"], "Burn Engine"),
            ("Birgi, God of Storytelling", "Creature — God", 3.0, ["R"], "Mana Engine"),
            ("Twisted Fealty", "Sorcery", 3.0, ["R"], "Combo Piece"),
            ("Twinflame", "Sorcery", 2.0, ["R"], "Combo Piece"),
            ("Dualcaster Mage", "Creature — Human Wizard", 3.0, ["R"], "Combo Piece"),
            ("Underworld Breach", "Enchantment", 2.0, ["R"], "Storm Engine"),
            ("Aetherflux Reservoir", "Artifact", 4.0, [], "Storm Wincon"),
            ("Grapeshot", "Sorcery", 2.0, ["R"], "Storm Finisher"),
            ("Brain Freeze", "Instant", 2.0, ["U"], "Storm Mill"),
            ("Mizzix's Mastery", "Sorcery", 4.0, ["R"], "Mass Recursion"),
            ("Past in Flames", "Sorcery", 4.0, ["R"], "Flashback Engine"),
            ("High Tide", "Instant", 1.0, ["U"], "Mana Multiplier"),
            ("Expressive Iteration", "Sorcery", 2.0, ["U", "R"], "Advantage"),
        ],
        "combos": ["Stella Lee + Twisted Fealty (Infinite Haste/Roles Damage)", "Dualcaster Mage + Twinflame (Infinite Hasty Dualcasters)"],
    },

    "Landfall / Lands Matter": {
        "theme": "Aceleración de tierras masiva, triggers de Landfall y destrucción/reanimación de tierras",
        "commanders": [
            {"name": "Omnath, Locus of Creation", "color_identity": ["W", "U", "R", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Elemental", "reason": "Dispara 4 vidas, 4 manás WUBRG y 4 daños a cada oponente por turno."},
            {"name": "Lord Windgrace", "color_identity": ["B", "R", "G"], "cmc": 5.0, "type_line": "Legendary Planeswalker — Windgrace", "reason": "Robo con descarte de tierras y reanimación de 2 tierras por turno."},
            {"name": "Aesi, Tyrant of Gyre Strait", "color_identity": ["U", "G"], "cmc": 6.0, "type_line": "Legendary Creature — Serpent Beast", "reason": "Tierra adicional por turno y robo de carta por cada tierra que entra."},
            {"name": "The Gitrog Monster", "color_identity": ["B", "G"], "cmc": 5.0, "type_line": "Legendary Creature — Frog Horror", "reason": "Robo masivo con tierras en cementerio y motor de combo cEDH con Dakmor Salvage."},
        ],
        "synergy_cards": [
            ("Lotus Cobra", "Creature — Snake", 2.0, ["G"], "Mana Generation"),
            ("Tireless Provisioner", "Creature — Elf Scout", 3.0, ["G"], "Treasure / Food"),
            ("Tireless Tracker", "Creature — Human Scout", 3.0, ["G"], "Clue Engine"),
            ("Scute Swarm", "Creature — Insect", 3.0, ["G"], "Token Swarm"),
            ("Avenger of Zendikar", "Creature — Elemental", 7.0, ["G"], "Mass Tokens"),
            ("Azusa, Lost but Seeking", "Creature — Human Monk", 3.0, ["G"], "Extra Lands"),
            ("Oracle of Mul Daya", "Creature — Elf Shaman", 4.0, ["G"], "Extra Lands/Top"),
            ("Ramunap Excavator", "Creature — Snake Cleric", 3.0, ["G"], "Graveyard Lands"),
            ("Crucible of Worlds", "Artifact", 3.0, [], "Graveyard Lands"),
            ("Conduit of Worlds", "Artifact", 4.0, ["G"], "Graveyard Lands"),
            ("Ancient Greenwarden", "Creature — Elemental", 6.0, ["G"], "Landfall Doubler"),
            ("Cultivator Colossus", "Creature — Plant Beast", 7.0, ["G"], "Draw/Drop"),
            ("Reshape the Earth", "Sorcery", 9.0, ["G"], "10 Lands Wincon"),
            ("Scapeshift", "Sorcery", 4.0, ["G"], "Mass Land Sac/Tutor"),
            ("Splendid Reclamation", "Sorcery", 4.0, ["G"], "Mass Land Return"),
        ],
        "combos": ["The Gitrog Monster + Dakmor Salvage + Discard Outlet (Infinite Dredge/Draw)", "Scapeshift + Valakut / Field of the Dead (Mass Lethal Damage/Zombies)"],
    },

    "Dragon Tribal": {
        "theme": "Dragones masivos, reducción de costes, daño aéreo arrollador y efectos de entrada",
        "commanders": [
            {"name": "The Ur-Dragon", "color_identity": ["W", "U", "B", "R", "G"], "cmc": 9.0, "type_line": "Legendary Creature — Dragon Avatar", "reason": "Eminencia que reduce en {1} todos los dragones desde la zona de comando."},
            {"name": "Miirym, Sentinel Wyrm", "color_identity": ["U", "R", "G"], "cmc": 6.0, "type_line": "Legendary Creature — Dragon", "reason": "Crea una copia token no legendaria de cada dragón que entra."},
            {"name": "Lathliss, Dragon Queen", "color_identity": ["R"], "cmc": 6.0, "type_line": "Legendary Creature — Dragon", "reason": "Crea un token dragón 5/5 con vuelo cada vez que lanzas un dragón."},
            {"name": "Tiamat", "color_identity": ["W", "U", "B", "R", "G"], "cmc": 7.0, "type_line": "Legendary Creature — Dragon God", "reason": "Tutora 5 dragones diferentes directamente a tu mano al entrar."},
        ],
        "synergy_cards": [
            ("Miirym, Sentinel Wyrm", "Creature — Dragon", 6.0, ["U", "R", "G"], "Token Duplicator"),
            ("Goldspan Dragon", "Creature — Dragon", 5.0, ["R"], "Treasure Ramp"),
            ("Old Gnawbone", "Creature — Dragon", 7.0, ["G"], "Mass Treasures"),
            ("Terror of the Peaks", "Creature — Dragon", 5.0, ["R"], "Burn Damage"),
            ("Scourge of Valkas", "Creature — Dragon", 5.0, ["R"], "Burn Damage"),
            ("Dragon Tempest", "Enchantment", 2.0, ["R"], "Haste/Burn"),
            ("Utvara Hellkite", "Creature — Dragon", 8.0, ["R"], "Token Engine"),
            ("Rivaz of the Claw", "Creature — Dragon Warlock", 3.0, ["B", "R"], "Mana/Recursion"),
            ("Klauth, Unrivaled Ancient", "Creature — Dragon", 7.0, ["R", "G"], "Mana Generation"),
            ("Dragon's Hoard", "Artifact", 3.0, [], "Mana/Draw"),
            ("Orb of Dragonkind", "Artifact", 2.0, ["R"], "Mana/Tutor"),
            ("Crucible of Fire", "Enchantment", 4.0, ["R"], "Dragon Buff"),
            ("Savage Ventmaw", "Creature — Dragon", 6.0, ["R", "G"], "Combat Mana"),
            ("Hellkite Charger", "Creature — Dragon", 6.0, ["R"], "Extra Combat"),
            ("Ganax, Astral Hunter", "Creature — Dragon", 5.0, ["R"], "Treasure"),
        ],
        "combos": ["Hellkite Charger + Savage Ventmaw / Old Gnawbone (Infinite Combat Steps)", "Scourge of Valkas + Miirym (Exponential Lethal Burn)"],
    },

    "Artifacts Matter / Cheerios": {
        "theme": "Sinergias de artefactos, reducción de costes, fabricación de constructos y combos de maná",
        "commanders": [
            {"name": "Urza, Lord High Artificer", "color_identity": ["U"], "cmc": 4.0, "type_line": "Legendary Creature — Human Artificer", "reason": "Transforma cada artefacto en un Mox Sapphire y juega cartas gratis de la biblioteca."},
            {"name": "Breya, Etherium Shaper", "color_identity": ["W", "U", "B", "R"], "cmc": 4.0, "type_line": "Legendary Artifact Creature — Human", "reason": "Entra con tópteros y ofrece daño, eliminación y ganancia de vidas sacrificando artefactos."},
            {"name": "Jhoira, Weatherlight Captain", "color_identity": ["U", "R"], "cmc": 4.0, "type_line": "Legendary Creature — Human Artificer", "reason": "Roba 1 carta cada vez que lanzas un hechizo histórico (artefacto o legendario)."},
            {"name": "Emry, Lurker of the Loch", "color_identity": ["U"], "cmc": 3.0, "type_line": "Legendary Creature — Merfolk Wizard", "reason": "Cuesta {1} menos por artefacto y relanza artefactos desde el cementerio."},
        ],
        "synergy_cards": [
            ("Etherium Sculptor", "Creature — Vedalken Artificer", 2.0, ["U"], "Cost Reducer"),
            ("Foundry Inspector", "Artifact Creature — Construct", 3.0, [], "Cost Reducer"),
            ("Sai, Master Thopterist", "Creature — Human Artificer", 3.0, ["U"], "Thopters/Draw"),
            ("Emry, Lurker of the Loch", "Creature — Merfolk Wizard", 3.0, ["U"], "Recursion"),
            ("Mystic Forge", "Artifact", 4.0, [], "Topdeck Cast"),
            ("Sensei's Divining Top", "Artifact", 1.0, [], "Draw Engine"),
            ("Kuldotha Forgemaster", "Artifact Creature — Construct", 5.0, [], "Artifact Tutor"),
            ("Bolas's Citadel", "Artifact", 6.0, ["B"], "Topdeck Engine"),
            ("Unwinding Clock", "Artifact", 4.0, [], "Untap Artifacts"),
            ("Isochron Scepter", "Artifact", 2.0, [], "Infinite Scepter"),
            ("Dramatic Reversal", "Instant", 2.0, ["U"], "Dramatic Combo"),
            ("Rings of Brighthearth", "Artifact", 3.0, [], "Copy Trigger"),
            ("Basalt Monolith", "Artifact", 3.0, [], "Infinite Mana"),
            ("Mishra's Bauble", "Artifact", 0.0, [], "Cheerio"),
            ("Urza's Bauble", "Artifact", 0.0, [], "Cheerio"),
        ],
        "combos": ["Isochron Scepter + Dramatic Reversal (Infinite Mana/Untap)", "Basalt Monolith + Rings of Brighthearth (Infinite Mana)", "Mystic Forge + Sensei's Divining Top + Cost Reducer (Draw Whole Deck)"],
    },

    "cEDH Fast Combo": {
        "theme": "Máxima eficiencia competitiva, combos compactos de 2 cartas y respuesta ultra-rápida",
        "commanders": [
            {"name": "Kinnan, Bonder Prodigy", "color_identity": ["U", "G"], "cmc": 2.0, "type_line": "Legendary Creature — Human Druid", "reason": "Duplica maná de no-tierras y pone criaturas gigantes en mesa instantáneamente."},
            {"name": "Najeela, the Blade-Blossom", "color_identity": ["W", "U", "B", "R", "G"], "cmc": 3.0, "type_line": "Legendary Creature — Human Warrior", "reason": "Combates infinitos de turno 2-3 con Derevi o Grim Hireling."},
            {"name": "Tymna the Weaver", "color_identity": ["W", "B"], "cmc": 3.0, "type_line": "Legendary Creature — Human Cleric", "reason": "Motor de ventaja competitiva insuperable en cEDH."},
            {"name": "Kraum, Ludevic's Opus", "color_identity": ["U", "R"], "cmc": 5.0, "type_line": "Legendary Creature — Zombie Horror", "reason": "Amenaza voladora con prisa que roba masivamente por las jugadas rivales."},
        ],
        "synergy_cards": [
            ("Thassa's Oracle", "Creature — Merfolk Wizard", 2.0, ["U"], "Wincon"),
            ("Demonic Consultation", "Instant", 1.0, ["B"], "Wincon Enabler"),
            ("Tainted Pact", "Instant", 2.0, ["B"], "Wincon Enabler"),
            ("Underworld Breach", "Enchantment", 2.0, ["R"], "Wincon Engine"),
            ("Brain Freeze", "Instant", 2.0, ["U"], "Storm Mill"),
            ("Lion's Eye Diamond", "Artifact", 0.0, [], "Fast Mana"),
            ("Ad Nauseam", "Instant", 5.0, ["B"], "Mass Draw"),
            ("Kinnan, Bonder Prodigy", "Creature — Human Druid", 2.0, ["U", "G"], "Engine"),
            ("Basalt Monolith", "Artifact", 3.0, [], "Kinnan Combo"),
            ("Hullbreaker Horror", "Creature — Kraken Horror", 7.0, ["U"], "Bounce Combo"),
            ("Dockside Extortionist", "Creature — Goblin Pirate", 2.0, ["R"], "Fast Mana"),
            ("Drannith Magistrate", "Creature — Human Cleric", 2.0, ["W"], "Lock"),
            ("Opposition Agent", "Creature — Human Rogue", 3.0, ["B"], "Tutor Steal"),
            ("Dauthi Voidwalker", "Creature — Dauthi Rogue", 2.0, ["B"], "Graveyard Hate"),
            ("Orcish Bowmasters", "Creature — Orc Archer", 2.0, ["B"], "Punish Draw"),
        ],
        "combos": ["Thassa's Oracle + Demonic Consultation (Instant Win)", "Underworld Breach + Brain Freeze + Lion's Eye Diamond (Infinite Mill/Win)", "Kinnan + Basalt Monolith (Infinite Colorless Mana)"],
    },

    "Voltron / Equipment": {
        "theme": "Equipar o encantar al comandante para eliminar jugadores por daño de comandante (21 daños)",
        "commanders": [
            {"name": "Sram, Senior Edificer", "color_identity": ["W"], "cmc": 2.0, "type_line": "Legendary Creature — Dwarf Advisor", "reason": "Roba carta por cada aura, equipo o vehículo lanzado por 2 manás."},
            {"name": "Galea, Kindler of Hope", "color_identity": ["W", "U", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Elf Knight", "reason": "Juega auras y equipos gratis desde el topdeck y equipa automáticamente."},
            {"name": "Wyleth, Soul of Steel", "color_identity": ["R", "W"], "cmc": 3.0, "type_line": "Legendary Creature — Human Warrior", "reason": "Roba cartas igual a todos los equipos y auras anexados cada vez que ataca."},
            {"name": "Light-Paws, Emperor's Voice", "color_identity": ["W"], "cmc": 2.0, "type_line": "Legendary Creature — Fox Advisor", "reason": "Tutora un aura directamente al campo cada vez que lanzas un aura."},
        ],
        "synergy_cards": [
            ("Stoneforge Mystic", "Creature — Kor Artificer", 2.0, ["W"], "Equipment Tutor"),
            ("Puresteel Paladin", "Creature — Human Knight", 2.0, ["W"], "Free Equip / Draw"),
            ("Danitha Capashen, Paragon", "Creature — Human Knight", 3.0, ["W"], "Cost Reducer"),
            ("Halvar, God of Battle", "Creature — God", 4.0, ["W"], "Auto-Attach / Double Strike"),
            ("Sigarda's Aid", "Enchantment", 1.0, ["W"], "Flash / Auto-Attach"),
            ("Sword of Feast and Famine", "Artifact — Equipment", 3.0, [], "Untap Lands / Protect"),
            ("Sword of Fire and Ice", "Artifact — Equipment", 3.0, [], "Draw / Burn"),
            ("Shadowspear", "Artifact — Equipment", 1.0, [], "Trample / Lifelink"),
            ("Colossus Hammer", "Artifact — Equipment", 1.0, [], "+10/+10 Beatdown"),
            ("Blackblade Reforged", "Legendary Artifact — Equipment", 2.0, [], "Scaling Power"),
            ("Hammer of Nazahn", "Legendary Artifact — Equipment", 4.0, [], "Indestructible/Attach"),
            ("Sunforger", "Artifact — Equipment", 3.0, ["R", "W"], "Instant Tutor Cast"),
            ("Kediss, Emberclaw Familiar", "Legendary Creature — Lizard", 2.0, ["R"], "Damage to All"),
            ("All That Glitters", "Enchantment — Aura", 2.0, ["W"], "Huge Power Boost"),
            ("Ethereal Armor", "Enchantment — Aura", 1.0, ["W"], "Huge Power Boost"),
        ],
        "combos": ["Godo, Bandit Warlord + Helm of the Host (Infinite Combat Steps)", "Sram + 0-CMC Equipments (Cheerio Draw Whole Deck)"],
    },

    "Enchantress / Pillowfort": {
        "theme": "Motores de robo por encantamientos, bloqueos de ataque y stax temático",
        "commanders": [
            {"name": "Sythis, Harvest's Hand", "color_identity": ["G", "W"], "cmc": 2.0, "type_line": "Legendary Enchantment Creature — Nymph", "reason": "Roba 1 carta y gana 1 vida por CADA encantamiento lanzado por solo 2 manás."},
            {"name": "Tuvasa the Sunlit", "color_identity": ["W", "U", "G"], "cmc": 3.0, "type_line": "Legendary Creature — Merfolk Shaman", "reason": "Roba carta en el primer encantamiento de cada turno y crece con ellos."},
            {"name": "Zur the Enchanter", "color_identity": ["W", "U", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Human Wizard", "reason": "Tutora y pone en juego cualquier encantamiento de 3 CMC o menos al atacar."},
            {"name": "Go-Shintai of Life's Origin", "color_identity": ["W", "U", "B", "R", "G"], "cmc": 4.0, "type_line": "Legendary Enchantment Creature — Shrine", "reason": "Genera santuarios y reanima encantamientos del cementerio."},
        ],
        "synergy_cards": [
            ("Enchantress's Presence", "Enchantment", 3.0, ["G"], "Draw Engine"),
            ("Argothian Enchantress", "Creature — Human", 2.0, ["G"], "Draw Engine"),
            ("Satyr Enchanter", "Creature — Satyr Druid", 3.0, ["G", "W"], "Draw Engine"),
            ("Mesa Enchantress", "Creature — Human", 3.0, ["W"], "Draw Engine"),
            ("Verduran Enchantress", "Creature — Human Druid", 3.0, ["G"], "Draw Engine"),
            ("Sterling Grove", "Enchantment", 2.0, ["G", "W"], "Shroud / Tutor"),
            ("Privileged Position", "Enchantment", 5.0, ["G", "W"], "Hexproof All"),
            ("Ghostly Prison", "Enchantment", 3.0, ["W"], "Pillowfort Tax"),
            ("Sphere of Safety", "Enchantment", 5.0, ["W"], "Mass Attack Tax"),
            ("Propaganda", "Enchantment", 3.0, ["U"], "Attack Tax"),
            ("Solitary Confinement", "Enchantment", 3.0, ["W"], "Immunity"),
            ("Sanctum Weaver", "Enchantment Creature — Dryad", 2.0, ["G"], "Mass Mana"),
            ("Serra's Sanctum", "Legendary Land", 0.0, [], "Mass Mana Land"),
            ("Destiny Spinner", "Enchantment Creature — Human", 2.0, ["G"], "Uncounterable"),
            ("Starfield of Nyx", "Enchantment", 5.0, ["W"], "Recursion / Beatdown"),
        ],
        "combos": ["Sanctum Weaver + Freed from the Real / Gauntlets of Light (Infinite Mana)", "Solemnity + Phyrexian Unlife / Glacial Chasm (Immunity to Damage)"],
    },

    "+1/+1 Counters / Proliferate": {
        "theme": "Crecimiento exponencial de contadores +1/+1, duplicación y mecánicas de Proliferar",
        "commanders": [
            {"name": "Atraxa, Praetors' Voice", "color_identity": ["W", "U", "B", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Phyrexian Angel", "reason": "Prolifera al final de cada turno con 4 habilidades de combate."},
            {"name": "Vorinclex, Monstrous Raider", "color_identity": ["G"], "cmc": 6.0, "type_line": "Legendary Creature — Phyrexian Praetor", "reason": "Duplica todos tus contadores y reduce a la mitad los de los oponentes."},
            {"name": "Marchesa, the Black Rose", "color_identity": ["U", "B", "R"], "cmc": 4.0, "type_line": "Legendary Creature — Human Noble", "reason": "Reanima cualquier criatura tuya con contador +1/+1 que muera."},
            {"name": "Shalai and Hallar", "color_identity": ["R", "G", "W"], "cmc": 4.0, "type_line": "Legendary Creature — Elf Angel", "reason": "Inflige 1 punto de daño al oponente cada vez que pones un contador +1/+1."},
        ],
        "synergy_cards": [
            ("Hardened Scales", "Enchantment", 1.0, ["G"], "Counter Booster"),
            ("Branching Evolution", "Enchantment", 3.0, ["G"], "Counter Doubler"),
            ("Doubling Season", "Enchantment", 5.0, ["G"], "Counter & Token Doubler"),
            ("Primal Vigor", "Enchantment", 5.0, ["G"], "Counter & Token Doubler"),
            ("Kami of Whispered Hopes", "Creature — Spirit", 3.0, ["G"], "Booster & Mana"),
            ("Deepglow Skate", "Creature — Fish", 5.0, ["U"], "Mass Counter Doubler"),
            ("Evolution Sage", "Creature — Elf Druid", 3.0, ["G"], "Landfall Proliferate"),
            ("Flux Channeler", "Creature — Human Wizard", 3.0, ["U"], "Spell Proliferate"),
            ("Inexorable Tide", "Enchantment", 5.0, ["U"], "Spell Proliferate"),
            ("Kalonian Hydra", "Creature — Hydra", 5.0, ["G"], "Attack Counter Doubler"),
            ("The Ozolith", "Artifact", 1.0, [], "Counter Storage"),
            ("Ozolith, the Shattered Spire", "Legendary Artifact", 2.0, ["G"], "Counter Booster"),
            ("All Will Be One", "Enchantment", 5.0, ["R"], "Burn Damage Machine"),
            ("The Red Terror", "Creature — Tyranid", 5.0, ["R"], "Infinite Combo"),
            ("Heliod, Sun-Crowned", "Legendary Enchantment Creature — God", 3.0, ["W"], "Lifegain Counters"),
        ],
        "combos": ["Shalai and Hallar + The Red Terror (Infinite Burn Damage)", "Heliod, Sun-Crowned + Walking Ballista (Infinite Machinegun Damage)"],
    },

    "Token Swarm / Go-Wide": {
        "theme": "Creación masiva de fichas, duplicadores de tokens y efectos de himno/overrun",
        "commanders": [
            {"name": "Rhys the Redeemed", "color_identity": ["G", "W"], "cmc": 1.0, "type_line": "Legendary Creature — Elf Warrior", "reason": "Crea tokens y duplica TODAS tus fichas por 6 manás."},
            {"name": "Cadira, Caller of the Small", "color_identity": ["G", "W"], "cmc": 3.0, "type_line": "Legendary Creature — Orc Ranger", "reason": "Duplica tus fichas en forma de conejos 1/1 cada vez que hace daño de combate."},
            {"name": "Jinnie Fay, Jetmir's Second", "color_identity": ["R", "G", "W"], "cmc": 3.0, "type_line": "Legendary Creature — Elf Druid", "reason": "Transforma cualquier ficha en perros 3/1 con vigilancia o gatos 2/2 con prisa."},
            {"name": "Krenko, Mob Boss", "color_identity": ["R"], "cmc": 4.0, "type_line": "Legendary Creature — Goblin Warrior", "reason": "Duplica el número total de tus trasgos al girarse."},
        ],
        "synergy_cards": [
            ("Anointed Procession", "Enchantment", 4.0, ["W"], "Token Doubler"),
            ("Parallel Lives", "Enchantment", 4.0, ["G"], "Token Doubler"),
            ("Mondrak, Glory Dominus", "Legendary Creature — Phyrexian Horror", 4.0, ["W"], "Token Doubler"),
            ("Ojer Taq, Deepest Foundation", "Legendary Creature — God", 6.0, ["W"], "Token Tripler"),
            ("Cathars' Crusade", "Enchantment", 5.0, ["W"], "Massive Buff"),
            ("Beastmaster Ascension", "Enchantment", 3.0, ["G"], "Overrun Buff"),
            ("Craterhoof Behemoth", "Creature — Beast", 8.0, ["G"], "Lethal Finisher"),
            ("Moonshaker Cavalry", "Creature — Spirit Knight", 8.0, ["W"], "White Craterhoof"),
            ("Jetmir, Nexus of Revels", "Legendary Creature — Demon Cat", 4.0, ["R", "G", "W"], "Overrun Commander"),
            ("Hero of Bladehold", "Creature — Human Knight", 4.0, ["W"], "Battle Cry Tokens"),
            ("Chatterfang, Squirrel General", "Legendary Creature — Squirrel Warrior", 3.0, ["B", "G"], "Squirrel Duplicator"),
            ("Mirkwood Bats", "Creature — Bat", 4.0, ["B"], "Token Drain"),
            ("Halo Fountain", "Artifact", 3.0, ["W"], "Tokens/Wincon"),
            ("Adeline, Resplendent Cathar", "Legendary Creature — Human Knight", 3.0, ["W"], "Attack Tokens"),
            ("Avenger of Zendikar", "Creature — Elemental", 7.0, ["G"], "Mass Plants"),
        ],
        "combos": ["Krenko, Mob Boss + Thornbite Staff / Umbral Mantle (Infinite Goblins)", "Chatterfang + Pitiless Plunderer (Infinite Squirrels & Deaths)"],
    },

    "Reanimator / Graveyard Recursion": {
        "theme": "Llenar el cementerio y reanimar amenazas gigantescas por 1-2 manás",
        "commanders": [
            {"name": "Meren of Clan Nel Toth", "color_identity": ["B", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Human Shaman", "reason": "Contadores de experiencia que reaniman criaturas gratis al final del turno."},
            {"name": "The Mimeoplasm", "color_identity": ["U", "B", "G"], "cmc": 5.0, "type_line": "Legendary Creature — Ooze", "reason": "Copia cualquier criatura de cualquier cementerio con contadores de otra criatura."},
            {"name": "Chainer, Nightmare Adept", "color_identity": ["B", "R"], "cmc": 4.0, "type_line": "Legendary Creature — Human Minion", "reason": "Otorga prisa y relanza criaturas descartando cartas."},
            {"name": "Sefris of the Hidden Ways", "color_identity": ["W", "U", "B"], "cmc": 3.0, "type_line": "Legendary Creature — Human Wizard", "reason": "Avanza en mazmorras con triggers de criaturas en cementerio y reanima al completarlas."},
        ],
        "synergy_cards": [
            ("Reanimate", "Sorcery", 1.0, ["B"], "Reanimation"),
            ("Animate Dead", "Enchantment — Aura", 2.0, ["B"], "Reanimation"),
            ("Necromancy", "Enchantment", 3.0, ["B"], "Instant Reanimation"),
            ("Entomb", "Instant", 1.0, ["B"], "Grave Tutor"),
            ("Buried Alive", "Sorcery", 3.0, ["B"], "Triple Grave Tutor"),
            ("Unmarked Grave", "Sorcery", 2.0, ["B"], "Grave Tutor"),
            ("Razaketh, the Foulblooded", "Legendary Creature — Demon", 8.0, ["B"], "Sac Tutor"),
            ("Vilis, Broker of Blood", "Legendary Creature — Demon", 8.0, ["B"], "Life Draw"),
            ("Archon of Cruelty", "Creature — Archon", 8.0, ["B"], "ETB Drain/Sac"),
            ("Jin-Gitaxias, Core Augur", "Legendary Creature — Phyrexian Praetor", 10.0, ["U"], "Hand Wipe"),
            ("Toxrill, the Corrosive", "Legendary Creature — Slug Horror", 7.0, ["U", "B"], "Slime Board Wipe"),
            ("Stitcher's Supplier", "Creature — Zombie", 1.0, ["B"], "Self-Mill"),
            ("Altar of Dementia", "Artifact", 2.0, [], "Sac / Mill"),
            ("Persist", "Sorcery", 2.0, ["B"], "Cheap Reanimate"),
            ("Victimize", "Sorcery", 3.0, ["B"], "2-Creature Reanimation"),
        ],
        "combos": ["Worldgorger Dragon + Animate Dead (Infinite Mana & ETB Triggers)", "Abdel Adrian + Animate Dead / Necromancy (Infinite Soldiers/ETBs)"],
    },

    "Blink / Flicker / ETB Value": {
        "theme": "Exiliar y regresar permanentes al campo repetidamente para disparar efectos de entrada",
        "commanders": [
            {"name": "Brago, King Eternal", "color_identity": ["W", "U"], "cmc": 4.0, "type_line": "Legendary Creature — Spirit Soldier", "reason": "Exilia y regresa cualquier número de permanentes no-tierra al hacer daño de combate."},
            {"name": "Elesh Norn, Mother of Machines", "color_identity": ["W"], "cmc": 5.0, "type_line": "Legendary Creature — Phyrexian Praetor", "reason": "Panharmonicon viviente que duplica todos tus ETBs y anula los de tus oponentes."},
            {"name": "Yorion, Sky Nomad", "color_identity": ["W", "U"], "cmc": 5.0, "type_line": "Legendary Creature — Bird Serpent", "reason": "Blink masivo de permanentes al final del turno."},
            {"name": "Roon of the Hidden Realm", "color_identity": ["W", "U", "G"], "cmc": 5.0, "type_line": "Legendary Creature — Rhino Soldier", "reason": "Exilia criaturas para regresarlas en el paso final."},
        ],
        "synergy_cards": [
            ("Ephemerate", "Instant", 1.0, ["W"], "Rebound Blink"),
            ("Teleportation Circle", "Enchantment", 4.0, ["W"], "End Step Blink"),
            ("Conjurer's Closet", "Artifact", 5.0, [], "End Step Blink"),
            ("Soulherder", "Creature — Spirit", 3.0, ["W", "U"], "End Step Blink"),
            ("Displacer Kitten", "Creature — Cat", 4.0, ["U"], "Spell Blink Engine"),
            ("Panharmonicon", "Artifact", 4.0, [], "ETB Doubler"),
            ("Elesh Norn, Mother of Machines", "Creature — Phyrexian Praetor", 5.0, ["W"], "ETB Doubler / Stax"),
            ("Reflector Mage", "Creature — Human Wizard", 3.0, ["W", "U"], "Bounce Bounce"),
            ("Sun Titan", "Creature — Giant Soldier", 6.0, ["W"], "Recursion"),
            ("Agent of Treachery", "Creature — Human Rogue", 7.0, ["U"], "Steal Permanents"),
            ("Spirited Companion", "Enchantment Creature — Dog", 2.0, ["W"], "Draw ETB"),
            ("Mulldrifter", "Creature — Elemental", 5.0, ["U"], "Draw 2 ETB"),
            ("Cloudblazer", "Creature — Human Bird", 5.0, ["W", "U"], "Draw/Life ETB"),
            ("Felidar Guardian", "Creature — Cat Beast", 4.0, ["W"], "Flicker Permanent"),
            ("Restoration Angel", "Creature — Angel", 4.0, ["W"], "Flash Flicker"),
        ],
        "combos": ["Displacer Kitten + Teferi, Time Raveler + Mana Rock (Infinite Draw/Bounce)", "Felidar Guardian + Restoration Angel / Kiki-Jiki (Infinite Tokens/ETBs)"],
    },

    "Superfriends / Planeswalkers": {
        "theme": "Acumulación de Planeswalkers, activación múltiple de lealtades y protección de emblemas",
        "commanders": [
            {"name": "Atraxa, Praetors' Voice", "color_identity": ["W", "U", "B", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Phyrexian Angel", "reason": "Prolifera la lealtad de todos tus Planeswalkers al final de cada turno."},
            {"name": "Commodore Guff", "color_identity": ["U", "R", "W"], "cmc": 4.0, "type_line": "Legendary Planeswalker — Guff", "reason": "Genera lealtad, roba cartas y dispara daño masivo por cada Planeswalker."},
            {"name": "Carth the Lion", "color_identity": ["B", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Human Warrior", "reason": "Aumenta en +1 el coste de lealtad de activación y tutora Planeswalkers."},
        ],
        "synergy_cards": [
            ("Doubling Season", "Enchantment", 5.0, ["G"], "Instant Ultimates"),
            ("Vorinclex, Monstrous Raider", "Creature — Phyrexian Praetor", 6.0, ["G"], "Instant Ultimates"),
            ("Deepglow Skate", "Creature — Fish", 5.0, ["U"], "Double Loyalty"),
            ("Ichormoon Gauntlet", "Artifact", 3.0, [], "Extra Turns / Proliferate"),
            ("The Chain Veil", "Legendary Artifact", 4.0, [], "Double Activations"),
            ("Teferi, Hero of Dominaria", "Legendary Planeswalker — Teferi", 5.0, ["W", "U"], "Draw / Untap / Exile"),
            ("Teferi, Time Raveler", "Legendary Planeswalker — Teferi", 3.0, ["W", "U"], "Silence / Bounce"),
            ("Oko, Thief of Crowns", "Legendary Planeswalker — Oko", 3.0, ["U", "G"], "Elk Machine"),
            ("Narset, Parter of Veils", "Legendary Planeswalker — Narset", 3.0, ["U"], "Draw Denial"),
            ("Ugin, the Spirit Dragon", "Legendary Planeswalker — Ugin", 8.0, [], "Board Wipe / Bolt"),
            ("Karn Liberated", "Legendary Planeswalker — Karn", 7.0, [], "Exile Threat"),
            ("Nicol Bolas, Dragon-God", "Legendary Planeswalker — Bolas", 5.0, ["U", "B", "R"], "All Loyalty Abilities"),
            ("Chandra, Awakened Inferno", "Legendary Planeswalker — Chandra", 6.0, ["R"], "Incounterable Emblems"),
            ("Liliana, Dreadhorde General", "Legendary Planeswalker — Liliana", 6.0, ["B"], "Tokens / Sac / Ultimate"),
            ("Tamiyo, Field Researcher", "Legendary Planeswalker — Tamiyo", 4.0, ["W", "U", "G"], "Omniscience Ultimate"),
        ],
        "combos": ["Doubling Season + Teferi / Tamiyo (Instant Game-Winning Emblems)", "The Chain Veil + Teferi, Temporal Archmage + 3 Mana Rocks (Infinite Loyalty & Mana)"],
    },

    "Wheels / Forced Draw": {
        "theme": "Descarte y robo masivo de 7 cartas continuo (Wheels), castigando oponentes con daño o drenaje",
        "commanders": [
            {"name": "Nekusar, the Mindrazer", "color_identity": ["U", "B", "R"], "cmc": 5.0, "type_line": "Legendary Creature — Zombie Wizard", "reason": "Inflige 1 daño a cada oponente cada vez que roban una carta."},
            {"name": "Xyris, the Writhing Storm", "color_identity": ["U", "R", "G"], "cmc": 5.0, "type_line": "Legendary Creature — Snake Leviathan", "reason": "Crea una serpiente 1/1 por cada carta que roban tus oponentes."},
            {"name": "The Locust God", "color_identity": ["U", "R"], "cmc": 6.0, "type_line": "Legendary Creature — God", "reason": "Crea un insecto 1/1 volador con prisa cada vez que tú robas una carta."},
            {"name": "Sheoldred, the Apocalypse", "color_identity": ["B"], "cmc": 4.0, "type_line": "Legendary Creature — Phyrexian Praetor", "reason": "Drena 2 vidas por cada robo enemigo y ganas 2 vidas por los tuyos."},
        ],
        "synergy_cards": [
            ("Wheel of Fortune", "Sorcery", 3.0, ["R"], "7-Card Wheel"),
            ("Windfall", "Sorcery", 3.0, ["U"], "Hand Size Wheel"),
            ("Timetwister", "Sorcery", 3.0, ["U"], "Grave Shuffle Wheel"),
            ("Reforge the Soul", "Sorcery", 5.0, ["R"], "Miracle Wheel"),
            ("Whispering Madness", "Sorcery", 4.0, ["U", "B"], "Cipher Wheel"),
            ("Sheoldred, the Apocalypse", "Creature — Phyrexian Praetor", 4.0, ["B"], "Drain Punisher"),
            ("Orcish Bowmasters", "Creature — Orc Archer", 2.0, ["B"], "Ping & Army"),
            ("Underworld Dreams", "Enchantment", 3.0, ["B"], "Draw Damage"),
            ("Fate Unraveler", "Enchantment Creature — Hag", 4.0, ["B"], "Draw Damage"),
            ("Megrim", "Enchantment", 3.0, ["B"], "Discard Damage"),
            ("Liliana's Caress", "Enchantment", 2.0, ["B"], "Discard Damage"),
            ("Waste Not", "Enchantment", 2.0, ["B"], "Discard Value Machine"),
            ("Notion Thief", "Creature — Human Rogue", 4.0, ["U", "B"], "Steal All Draws"),
            ("Narset, Parter of Veils", "Planeswalker — Narset", 3.0, ["U"], "Lockout Wheel"),
            ("Teferi's Puzzle Box", "Artifact", 4.0, [], "Every Turn Wheel"),
        ],
        "combos": ["Notion Thief / Narset + Windfall / Wheel of Fortune (Opponents Discard Entire Hand)", "Nekusar + Peer into the Abyss (Instant 35-40 Damage Kill)"],
    },

    "Demons Tribal / Burn & Draw": {
        "theme": "Demonios colosales que castigan la mesa, roban cartas masivas con Be'lakor y disparan daño de entrada",
        "commanders": [
            {"name": "Be'lakor, the Dark Master", "color_identity": ["U", "B", "R"], "cmc": 6.0, "type_line": "Legendary Creature — Demon Noble", "reason": "Robo masivo igual al número de Demonios y daño directo al entrar cualquier demonio."},
            {"name": "Rakdos, the Showstopper", "color_identity": ["B", "R"], "cmc": 6.0, "type_line": "Legendary Creature — Demon", "reason": "Lanza monedas para destruir todas las criaturas no demonios, no diablos, no diablillos."},
            {"name": "Raphael, Fiendish Savior", "color_identity": ["B", "R"], "cmc": 5.0, "type_line": "Legendary Creature — Demon Tiefling", "reason": "Otorga vínculo vital (+1/+1) a todos tus Demonios y crea tokens de Diablillo."},
            {"name": "K'rrik, Son of Yawgmoth", "color_identity": ["B"], "cmc": 7.0, "type_line": "Legendary Creature — Phyrexian Minion", "reason": "Paga maná pirexiano con vidas para lanzar demonios rápidamente."},
        ],
        "synergy_cards": [
            ("Vilis, Broker of Blood", "Legendary Creature — Demon", 8.0, ["B"], "Life Draw Engine"),
            ("Razaketh, the Foulblooded", "Legendary Creature — Demon", 8.0, ["B"], "Sac Tutor Engine"),
            ("Archfiend of Despair", "Creature — Demon", 8.0, ["B"], "Double Damage / Anti-Lifegain"),
            ("Bloodthirster", "Creature — Demon", 6.0, ["R"], "Triple Combat Steps"),
            ("Bloodletter of Aclazotz", "Creature — Demon", 4.0, ["B"], "Double Life Loss"),
            ("Burning-Rune Demon", "Creature — Demon Berserker", 6.0, ["B"], "Double Tutor ETB"),
            ("Lord of the Void", "Creature — Demon", 7.0, ["B"], "Steal Creatures from Deck"),
            ("Herald of Torment", "Enchantment Creature — Demon", 3.0, ["B"], "Flyer / Bestow"),
            ("Doom Whisperer", "Creature — Demon Nightmare", 5.0, ["B"], "Surveil 2 On Demand"),
            ("Harvester of Souls", "Creature — Demon", 6.0, ["B"], "Death Draw Trigger"),
            ("Demon of Dark Schemes", "Creature — Demon", 6.0, ["B"], "Mass -2/-2 & Reanimate"),
            ("Archfiend of Ifnir", "Creature — Demon", 5.0, ["B"], "-1/-1 Counters on Discard"),
            ("Taborax, Hope's Demise", "Legendary Creature — Demon Cleric", 3.0, ["B"], "Death Growth & Draw"),
            ("Liliana's Contract", "Enchantment", 5.0, ["B"], "Draw 4 & Win with 4 Demons"),
            ("Warstorm Surge", "Enchantment", 6.0, ["R"], "Double ETB Power Damage"),
            ("Reflections of Littjara", "Enchantment", 5.0, ["U"], "Copy All Demon Spells"),
            ("Herald's Horn", "Artifact", 3.0, [], "Cost Reducer & Demon Draw"),
            ("Urza's Incubator", "Artifact", 3.0, [], "Demon Cost -2"),
            ("Vanquisher's Banner", "Artifact", 5.0, [], "Demon Anthem & Cast Draw"),
            ("Kindred Discovery", "Enchantment", 5.0, ["U"], "Demon Attack & ETB Draw"),
            ("Patriarch's Bidding", "Sorcery", 5.0, ["B"], "Mass Demon Reanimation"),
            ("Haunting Voyage", "Sorcery", 6.0, ["B"], "Foretell Mass Demon Reanimate"),
            ("Roaming Throne", "Artifact Creature — Golem", 4.0, [], "Double All Demon Triggers"),
        ],
        "combos": ["Be'lakor + Liliana's Contract (Draw 4 Cards & Instant Win Condition)", "Be'lakor + Reflections of Littjara / Roaming Throne (Quadruple ETB Demon Damage)"],
    },

    "Vampires Tribal / Blood Drain": {
        "theme": "Enjambre de Vampiros con contadores +1/+1, drenaje continuo de vidas y creación de tokens",
        "commanders": [
            {"name": "Edgar Markov", "color_identity": ["W", "B", "R"], "cmc": 6.0, "type_line": "Legendary Creature — Vampire Noble", "reason": "Eminence: crea un Vampiro 1/1 gratis cada vez que lanzas cualquier Vampiro."},
            {"name": "Vito, Thorn of the Dusk Rose", "color_identity": ["B"], "cmc": 3.0, "type_line": "Legendary Creature — Vampire Cleric", "reason": "Convierte toda tu ganancia de vidas en daño directo letal al oponente."},
            {"name": "Strefan, Maurer Progenitor", "color_identity": ["B", "R"], "cmc": 4.0, "type_line": "Legendary Creature — Vampire Noble", "reason": "Genera fichas de Sangre y pone Vampiros colosales gratis al atacar."},
            {"name": "Elenda, the Dusk Rose", "color_identity": ["W", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Vampire Knight", "reason": "Crecimiento continuo y explosión masiva de vampiros 1/1 con lifelink al morir."},
        ],
        "synergy_cards": [
            ("Bloodline Keeper", "Creature — Vampire", 4.0, ["B"], "Lord & Token Generator"),
            ("Captivating Vampire", "Creature — Vampire", 3.0, ["B"], "Lord & Steal Creatures"),
            ("Vampire Nighthawk", "Creature — Vampire Shaman", 3.0, ["B"], "Lifelink / Deathtouch / Flying"),
            ("Cordials Vampire", "Creature — Vampire", 2.0, ["B"], "Mass Vampire +1/+1 Counters"),
            ("Knight of the Ebon Legion", "Creature — Vampire Knight", 1.0, ["B"], "Aggro 1-Drop"),
            ("Champion of Dusk", "Creature — Vampire Knight", 5.0, ["B"], "Mass Vampire Draw"),
            ("Twilight Prophet", "Creature — Vampire Cleric", 4.0, ["B"], "Ascend Drain & Draw"),
            ("Cruel Celebrant", "Creature — Vampire", 2.0, ["W", "B"], "Aristocrat Drain"),
            ("Blood Artist", "Creature — Vampire", 2.0, ["B"], "Death Drain"),
            ("Drana, Liberator of Malakir", "Creature — Vampire Ally", 3.0, ["B"], "Combat +1/+1 Counters"),
            ("Sanctum Seeker", "Creature — Vampire Knight", 4.0, ["B"], "Attack Drain Trigger"),
            ("Crossway Troublemakers", "Creature — Vampire", 6.0, ["B"], "Lifelink & Deathtouch Draw"),
            ("Herald's Horn", "Artifact", 3.0, [], "Vampire Cost -1 & Draw"),
            ("Urza's Incubator", "Artifact", 3.0, [], "Vampire Cost -2"),
            ("Vanquisher's Banner", "Artifact", 5.0, [], "Vampire Anthem & Draw"),
            ("Patriarch's Bidding", "Sorcery", 5.0, ["B"], "Mass Vampire Reanimate"),
        ],
        "combos": ["Vito + Exquisite Blood (Infinite Drain Loop Kill)", "Edgar Markov + Bloodline Keeper (Overwhelming Vampire Army)"],
    },

    "Elves Tribal / Mana Dorks": {
        "theme": "Generación explosiva de maná con elfos dorks, robo masivo por lanzamiento y final con Craterhoof",
        "commanders": [
            {"name": "Lathril, Blade of the Elves", "color_identity": ["B", "G"], "cmc": 4.0, "type_line": "Legendary Creature — Elf Noble", "reason": "Crea elfos por daño de combate y drena 10 vidas girando 10 elfos."},
            {"name": "Ezuri, Renegade Leader", "color_identity": ["G"], "cmc": 3.0, "type_line": "Legendary Creature — Elf Warrior", "reason": "Regenera elfos y otorga +3/+3 y Arrollar repetible con maná infinito."},
            {"name": "Marwyn, the Nurturer", "color_identity": ["G"], "cmc": 3.0, "type_line": "Legendary Creature — Elf Druid", "reason": "Genera maná verde igual a su poder que crece con cada elfo."},
            {"name": "Rhys the Redeemed", "color_identity": ["G", "W"], "cmc": 1.0, "type_line": "Legendary Creature — Elf Warrior", "reason": "Duplica todos tus tokens en mesa cada turno."},
        ],
        "synergy_cards": [
            ("Llanowar Elves", "Creature — Elf Druid", 1.0, ["G"], "1-Mana Dork"),
            ("Elvish Mystic", "Creature — Elf Druid", 1.0, ["G"], "1-Mana Dork"),
            ("Fyndhorn Elves", "Creature — Elf Druid", 1.0, ["G"], "1-Mana Dork"),
            ("Priest of Titania", "Creature — Elf Druid", 2.0, ["G"], "Mass Green Mana per Elf"),
            ("Elvish Archdruid", "Creature — Elf Druid", 3.0, ["G"], "Lord & Mass Green Mana"),
            ("Elvish Champion", "Creature — Elf", 3.0, ["G"], "Lord & Forestwalk"),
            ("Wirewood Symbiote", "Creature — Insect", 1.0, ["G"], "Untap Dork & Bounce Elf"),
            ("Quirion Ranger", "Creature — Elf", 1.0, ["G"], "Untap Dork"),
            ("Circle of Dreams Druid", "Creature — Elf Druid", 3.0, ["G"], "Gaea's Cradle Creature"),
            ("Beast Whisperer", "Creature — Elf Druid", 4.0, ["G"], "Draw on Creature Cast"),
            ("Imperious Perfect", "Creature — Elf Warrior", 3.0, ["G"], "Lord & Elf Generator"),
            ("Heritage Druid", "Creature — Elf Druid", 1.0, ["G"], "Tap 3 Elves for 3 Mana"),
            ("Craterhoof Behemoth", "Creature — Beast", 8.0, ["G"], "Trample Overrun Win"),
            ("Finale of Devastation", "Sorcery", 2.0, ["G"], "Tutor & +X/+X Haste Overrun"),
            ("Realmwalker", "Creature — Shapeshifter", 3.0, ["G"], "Cast Elves from Top of Library"),
        ],
        "combos": ["Priest of Titania / Archdruid + Staff of Domination / Umbral Mantle (Infinite Mana & Draw)", "Lathril + 10 Elves + Seedborn Muse (Drain 40 Life across Turn Cycle)"],
    },

    "Zombies Tribal / Reanimate": {
        "theme": "Horda imparable de no-muertos, recursión continua desde el cementerio y aristocrats",
        "commanders": [
            {"name": "Wilhelt, the Rotcleaver", "color_identity": ["U", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Zombie Warrior", "reason": "Crea tokens Decayed cuando mueren zombis y roba cartas sacrificando no-muertos."},
            {"name": "The Scarab God", "color_identity": ["U", "B"], "cmc": 5.0, "type_line": "Legendary Creature — God", "reason": "Drena vidas y hace Scry por cada zombi, y crea copias 4/4 zombi de cualquier cementerio."},
            {"name": "Gisa and Geralf", "color_identity": ["U", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Human Wizard", "reason": "Auto-millea 4 cartas y lanza un Zombi desde el cementerio cada turno."},
            {"name": "Varina, Lich Queen", "color_identity": ["W", "U", "B"], "cmc": 4.0, "type_line": "Legendary Creature — Zombie Wizard", "reason": "Roba y descarta por cada zombi atacante y exilia cartas para crear zombis."},
        ],
        "synergy_cards": [
            ("Gravecrawler", "Creature — Zombie", 1.0, ["B"], "Cast from Graveyard Engine"),
            ("Cryptbreaker", "Creature — Zombie", 1.0, ["B"], "Discard Zombie & Tap 3 Draw"),
            ("Diregraf Captain", "Creature — Zombie Soldier", 3.0, ["U", "B"], "Lord & Death Ping"),
            ("Death Baron", "Creature — Zombie Wizard", 3.0, ["B"], "Lord & Deathtouch"),
            ("Lord of the Accursed", "Creature — Zombie", 3.0, ["B"], "Lord & Menace"),
            ("Undead Augur", "Creature — Zombie Wizard", 2.0, ["B"], "Death Draw Engine"),
            ("Diregraf Colossus", "Creature — Zombie Giant", 3.0, ["B"], "Cast Token Engine"),
            ("Champion of the Perished", "Creature — Zombie", 1.0, ["B"], "Growth Aggro 1-Drop"),
            ("Headless Rider", "Creature — Zombie", 3.0, ["B"], "Death Token Engine"),
            ("Zombie Master", "Creature — Zombie", 3.0, ["B"], "Swampwalk & Regenerate"),
            ("Rooftop Storm", "Enchantment", 6.0, ["U"], "Cast Zombies for {0} Mana"),
            ("Endless Ranks of the Dead", "Enchantment", 4.0, ["B"], "Double Zombie Army"),
            ("Patriarch's Bidding", "Sorcery", 5.0, ["B"], "Mass Zombie Reanimate"),
            ("Phyrexian Altar", "Artifact", 3.0, [], "Sac for Mana Engine"),
        ],
        "combos": ["Gravecrawler + Phyrexian Altar + Diregraf Captain / Wilhelt (Infinite Death Triggers & Kill)", "Rooftop Storm + Gravecrawler + Sac Outlet (Infinite Storm & ETB)"],
    },
}

# -----------------------------------------------------------------------------
# ARCHETYPE KEY ALIASES (For backward compatibility & short-name lookups)
# -----------------------------------------------------------------------------
_ALIASES = {
    "Aristocrats": "Aristocrats / Sacrifice",
    "Spellslinger": "Spellslinger / Storm",
    "Landfall": "Landfall / Ramp",
    "Dragons Tribal": "Dragons Tribal",
    "Dragons": "Dragons Tribal",
    "Artifacts Matter": "Artifacts / Urza Engine",
    "Artifacts": "Artifacts / Urza Engine",
    "cEDH Combo": "cEDH Fast Combo",
    "cEDH": "cEDH Fast Combo",
    "Voltron": "Voltron / Equipment & Auras",
    "Enchantress": "Enchantress / Shrines",
    "+1/+1 Counters": "+1/+1 Counters / Proliferate",
    "Token Swarm": "Token Swarm / Go-Wide",
    "Tokens": "Token Swarm / Go-Wide",
    "Reanimator": "Reanimator / Graveyard Recursion",
    "Blink": "Blink / Flicker / ETB Value",
    "Superfriends": "Superfriends / Planeswalkers",
    "Wheels": "Wheels / Forced Draw",
    "Demons": "Demons Tribal / Burn & Draw",
    "Demons Tribal": "Demons Tribal / Burn & Draw",
    "Demon Tribal": "Demons Tribal / Burn & Draw",
    "Demon": "Demons Tribal / Burn & Draw",
    "Vampires": "Vampires Tribal / Blood Drain",
    "Vampires Tribal": "Vampires Tribal / Blood Drain",
    "Vampire Tribal": "Vampires Tribal / Blood Drain",
    "Vampire": "Vampires Tribal / Blood Drain",
    "Elves": "Elves Tribal / Mana Dorks",
    "Elves Tribal": "Elves Tribal / Mana Dorks",
    "Elf Tribal": "Elves Tribal / Mana Dorks",
    "Elf": "Elves Tribal / Mana Dorks",
    "Zombies": "Zombies Tribal / Reanimate",
    "Zombies Tribal": "Zombies Tribal / Reanimate",
    "Zombie Tribal": "Zombies Tribal / Reanimate",
    "Zombie": "Zombies Tribal / Reanimate",
    "Tribal": "Demons Tribal / Burn & Draw",
    "Tribal / Kindred": "Demons Tribal / Burn & Draw",
    "Kindred": "Demons Tribal / Burn & Draw",
    "Eldrazi": "Eldrazi / Big Mana Colorless",
    "Stax": "Stax / Hatebears & Resource Denial",
    "Infect": "Infect / Toxic / Poison Proliferate",
    "Group Hug": "Group Hug / Extra Resources",
    "Chaos": "Chaos / Coin Flip & Randomness",
    "Cascade": "Cascade / Free Casting",
    "Mutate": "Mutate / Creature Stacking",
    "Lifegain": "Lifegain / Soul Sisters",
    "Graveyard Dredge": "Graveyard Dredge / Self-Mill",
    "Burn": "Burn / Group Slug",
}

for alias_k, canonical_k in _ALIASES.items():
    if canonical_k in ARCHETYPE_DEFINITIONS and alias_k not in ARCHETYPE_DEFINITIONS:
        ARCHETYPE_DEFINITIONS[alias_k] = ARCHETYPE_DEFINITIONS[canonical_k]


def resolve_card_metadata(card_name: str) -> Tuple[float, List[str], str, float]:
    """
    Resolves (cmc, colors, type_line, price_usd) for any card name using:
    1. CARD_METADATA_REGISTRY (exact & case-insensitive)
    2. Front-face lookup for split/DFC cards
    3. Scryfall cached data or safe defaults
    """
    name_clean = (card_name or "").strip()
    if not name_clean:
        return (0.0, [], "Card", 1.0)

    name_lower = name_clean.lower()
    
    # 1. Exact match in registry
    if name_clean in CARD_METADATA_REGISTRY:
        return CARD_METADATA_REGISTRY[name_clean]
    
    for k, v in CARD_METADATA_REGISTRY.items():
        if k.lower() == name_lower:
            return v
            
    # Front face match
    if " // " in name_clean or " / " in name_clean:
        front = name_clean.split(" // ")[0].split(" / ")[0].strip()
        for k, v in CARD_METADATA_REGISTRY.items():
            if k.lower() == front.lower():
                return v

    # 2. Try Scryfall in-memory cache lookup
    try:
        from ..scryfall.client import ScryfallClient
        client = ScryfallClient()
        card = client.get_card_by_name(name_clean)
        if card:
            cmc = float(card.cmc) if card.cmc is not None else 0.0
            colors = card.colors or []
            type_l = card.type_line or "Card"
            price = 2.50
            if card.prices and card.prices.usd:
                price = float(card.prices.usd)
            return (cmc, colors, type_l, price)
    except Exception:
        pass

    # 3. Default fallback
    return (2.0, [], "Card", 2.0)


